# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-24 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club', to='skyrock.Club'),
        ),
        migrations.AddField(
            model_name='student',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
