# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-12-02 03:44
from __future__ import unicode_literals

from django.db import migrations
import enumfields.fields
import skyrock.enums


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0002_auto_20191124_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='payment_status',
            field=enumfields.fields.EnumField(default='pending', enum=skyrock.enums.PaymentStatus, max_length=50),
        ),
    ]
