# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-11 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import enumfields.fields
import skyrock.enums


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0003_client_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrollment',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=enumfields.fields.EnumField(default='none', enum=skyrock.enums.BookingStatus, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=enumfields.fields.EnumField(default='active', enum=skyrock.enums.ClientStatus, max_length=50),
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=enumfields.fields.EnumField(default='active', enum=skyrock.enums.SessionStatus, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=enumfields.fields.EnumField(default='active', enum=skyrock.enums.StudentStatus, max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
