# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-12 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0004_auto_20200111_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
