# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-15 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import enumfields.fields
import skyrock.enums
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0005_auto_20200112_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('description', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('short_id', models.CharField(default='SP', max_length=5)),
                ('name', models.CharField(default='SP', max_length=50)),
                ('enrollments', models.IntegerField()),
                ('active_students', models.IntegerField()),
                ('inactive_students', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=enumfields.fields.EnumField(default='other', enum=skyrock.enums.PaymentMethds, max_length=50),
        ),
    ]
