# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-15 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0006_auto_20200115_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
