# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-15 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0008_auto_20200115_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
