# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-16 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0009_student_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='active_students',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='enrollments',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='inactive_students',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
