# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-19 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0012_auto_20200119_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='status',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
