# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-19 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0013_trial_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='teaching_record',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
