# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-21 11:43
from __future__ import unicode_literals

from django.db import migrations
import enumfields.fields
import skyrock.enums


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0015_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='attendance_status',
            field=enumfields.fields.EnumField(default='none', enum=skyrock.enums.AttendanceStatus, max_length=50),
        ),
    ]
