# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-27 08:21
from __future__ import unicode_literals

from django.db import migrations
import enumfields.fields
import skyrock.enums


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0016_booking_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=enumfields.fields.EnumField(default='active', enum=skyrock.enums.BookingStatus, max_length=50),
        ),
    ]
