# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-02-04 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0017_auto_20200127_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='skyrock.Student'),
        ),
    ]
