# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-02-20 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0021_auto_20200220_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentnote',
            name='student',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note', to='skyrock.Student'),
        ),
    ]
