# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-07 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0023_sessionnote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionnote',
            old_name='sesssion',
            new_name='session',
        ),
    ]
