# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-08 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import enumfields.fields
import skyrock.enums
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0024_auto_20200307_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('location', models.CharField(max_length=100)),
                ('status', enumfields.fields.EnumField(default='active', enum=skyrock.enums.SessionStatus, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
