# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-08 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0025_camp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='club_relation',
        ),
    ]
