# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-08 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0026_remove_badge_club_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
