# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-08 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0027_auto_20200308_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='skyrock.Student'),
        ),
    ]
