# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-08 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import skyrock.enums
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0028_auto_20200308_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('week', models.IntegerField(default=1)),
                ('location', models.CharField(max_length=100)),
                ('club', models.CharField(blank=True, db_index=True, max_length=50)),
                ('status', enumfields.fields.EnumField(default='active', enum=skyrock.enums.SessionStatus, max_length=50)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('session_type', enumfields.fields.EnumField(default='None', enum=skyrock.enums.SessionType, max_length=50)),
                ('student_amount', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('week', models.IntegerField(default=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='camp',
            name='weeks',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='campweek',
            name='camp',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campweek', to='skyrock.Camp'),
        ),
        migrations.AddField(
            model_name='campsession',
            name='camp',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campsession', to='skyrock.Camp'),
        ),
        migrations.AddField(
            model_name='campsession',
            name='teacher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campsession', to='skyrock.Teacher'),
        ),
    ]
