# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-08 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import enumfields.fields
import skyrock.enums


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0029_auto_20200308_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campsession',
            name='name',
        ),
        migrations.AddField(
            model_name='campsession',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='campsession',
            name='session_type',
            field=enumfields.fields.EnumField(default='None', enum=skyrock.enums.CampSessionType, max_length=50),
        ),
    ]
