# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-08 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0030_auto_20200308_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='camp_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='skyrock.CampSession'),
        ),
    ]
