# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-08 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import skyrock.enums
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0031_booking_camp_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('attendance', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', enumfields.fields.EnumField(default='active', enum=skyrock.enums.BookingStatus, max_length=50)),
                ('teaching_record', models.CharField(blank=True, max_length=500, null=True)),
                ('attendance_status', enumfields.fields.EnumField(default='none', enum=skyrock.enums.AttendanceStatus, max_length=50)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skyrock.Client')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campbookings', to='skyrock.CampSession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campbookings', to='skyrock.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='camp_session',
        ),
    ]
