# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-09 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0032_auto_20200308_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('badges', models.ManyToManyField(blank=True, to='skyrock.Badge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='campbooking',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='club',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_club',
        ),
        migrations.AddField(
            model_name='studentclub',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club', to='skyrock.Club'),
        ),
        migrations.AddField(
            model_name='studentclub',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='skyrock.Student'),
        ),
    ]
