# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-09 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0037_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campsession',
            name='week',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessionweek', to='skyrock.CampWeek'),
        ),
    ]
