# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-06 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0039_auto_20200329_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='campbooking',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='client',
            name='hours_remaining',
        ),
        migrations.RemoveField(
            model_name='client',
            name='total_hours_purchased',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hours',
        ),
    ]
