# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-19 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyrock', '0041_auto_20200407_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
